### ISSUE TITLE
Milestone branch sync is stuck: milestone/scan-issues-07092026

### ISSUE THREAD

**Issue by stservice** [stSoftwareAU/VibeCoder#1542]
## Milestone sync merge fails the repo's own check — needs a human

Merging `main` into `milestone/scan-issues-07092026` in `stSoftwareAU/VibeCoder` produced a tree that fails the repository's own check (a type error, or whatever else that check enforces — a stale lockfile under `--frozen`, say), so it was **not pushed** and the local merge was discarded (Issue #974).

Git reported no conflict: both sides were internally consistent and only their combination is not, which is how the same wiring was lost three times before this gate existed (#928, #796).

Check output:

```
Refused to push the merge of 'main' into 'milestone/scan-issues-07092026': the merged tree does not pass the repository's own check (Issue #974) — deno task check in /home/vibe/auto-issue-work/VibeCoder/worker/deno failed (exit 1)
    at file:///home/vibe/auto-issue-work/VibeCoder/worker/deno/lib/spawn_chokepoint_scan.ts:290:19

TS2305 [ERROR]: Module '"file:///home/vibe/auto-issue-work/VibeCoder/worker/deno/lib/spawn_chokepoint_scan.ts"' has no exported member 'IndirectSpawnRules'.
  type IndirectSpawnRules,
       ~~~~~~~~~~~~~~~~~~
    at file:///home/vibe/auto-issue-work/VibeCoder/worker/deno/tests/spawn_chokepoint_scan_test.ts:14:8

TS2304 [ERROR]: Cannot find name 'DOCKER_RULES'.
    DOCKER_RULES,
    ~~~~~~~~~~~~
    at file:///home/vibe/auto-issue-work/VibeCoder/worker/deno/tests/spawn_chokepoint_scan_test.ts:92:5

TS2304 [ERROR]: Cannot find name 'DOCKER_RULES'.
    DOCKER_RULES,
    ~~~~~~~~~~~~
    at file:///home/vibe/auto-issue-work/VibeCoder/worker/deno/tests/spawn_chokepoint_scan_test.ts:111:5

TS2304 [ERROR]: Cannot find name 'DOCKER_RULES'.
    DOCKER_RULES,
    ~~~~~~~~~~~~
    at file:///home/vibe/auto-issue-work/VibeCoder/worker/deno/tests/spawn_chokepoint_scan_test.ts:128:5

TS2304 [ERROR]: Cannot find name 'DOCKER_RULES'.
    DOCKER_RULES,
    ~~~~~~~~~~~~
    at file:///home/vibe/auto-issue-work/VibeCoder/worker/deno/tests/spawn_chokepoint_scan_test.ts:146:5

TS2353 [ERROR]: Object literal may only specify known properties, and 'rules' does not exist in type 'DirectSpawnScanOptions'.
      rules: DOCKER_RULES,
      ~~~~~
    at file:///home/vibe/auto-issue-work/VibeCoder/worker/deno/tests/spawn_chokepoint_scan_test.ts:181:7

TS2304 [ERROR]: Cannot find name 'DOCKER_RULES'.
      rules: DOCKER_RULES,
             ~~~~~~~~~~~~
    at file:///home/vibe/auto-issue-work/VibeCoder/worker/deno/tests/spawn_chokepoint_scan_test.ts:181:14

Found 31 errors.

error: Type checking failed.
```

Resolve the merge by hand on `milestone/scan-issues-07092026`. The sync will keep refusing to push until the merged tree compiles.

**Comment by nleck** [comment]
Resolved. The merge is pushed and PR #1557 (the rollup to `main`) has merged, so `milestone/scan-issues-07092026` is no longer diverged.

The type errors in the report were the visible end of a semantic conflict, not the problem itself. Two independently evolved implementations of the same spawn-chokepoint check had to be reconciled — `scanContentForVariableBinarySpawn` (Issue #1227) on `main` versus `IndirectSpawnRules` (Issue #1378) on the branch — where **neither contained the other**.

**#1378 survives on the merits.** Its second signal is exactly #1227's rule, and it adds one #1227 has no equivalent of (a generic wrapper called with the literal binary, `runWithTimeout("gh", …)`), plus a whole-file scan that catches a call split over several lines. Strict superset on detection.

**What #1227 knew and #1378 did not, now ported:** its allowlists recorded triaged false positives. `prerequisite_install_plan.ts` names `gh`/`git` as *package data* (`brewFormula("gh", "gh")` reads to the argv-head pattern as a command array) and only ever spawns the package manager. Without that entry the tree-wide scan tests fail — which is how the omission was caught rather than assumed. Its two further `git` entries turned out unnecessary: #1378 also demands an indirect construction in the same file, and neither module has one.

Also kept from `main`, which taking the branch wholesale would have dropped: `stripLineAndBlockComments` and `walkTsFiles` stay exported, because `redact_truncate_order_check.ts` and `tmp_state_dir_check.ts` import both.

`deno task check` — the Issue #974 gate that was refusing the push — now passes, along with `check:manifests` and the full unit suite (19467 parallel, 64 serial, 0 failed).

Two prevention issues filed so this does not recur: **#1558** (milestone branches are only synced from `main` at rollup time, so divergence compounds) and **#1559** (a conflicted sync escalates on sight, including the cases the worker could resolve itself).
