### ISSUE TITLE
Milestone sync: send a failed verification gate back to the agent rung with the compiler output (semantic conflicts), not straight to a human

### ISSUE THREAD

**Issue by nleck** [stSoftwareAU/VibeCoder#1965]
## Summary
A milestone sync whose textual conflicts are all resolved can still produce a tree that does not compile, because the default branch changed an interface the milestone branch implements somewhere git never saw a conflict. Today that gate failure goes straight to a human (`MilestoneConflictEscalation` from `gatedResolved`). It should go back to the agent rung once, with the gate's output, on the same clone.

## Evidence
`stSoftwareAU/GRQ-AutoTrader#292` (the human sync of `Develop` into `milestone/168-…`, 11 September 2026): git reported exactly one conflict, a paragraph of `docs/development.md`. After resolving it, `cargo check --workspace --all-targets` failed:

```text
error[E0046]: not all trait items implemented, missing: `find_by_client_order_id`
   --> crates/control/tests/runtime.rs:394:1
```

`Develop` (#284) had added a method to the `Broker` trait; the milestone branch's test fake `StopEngagingSession` predates it and does not implement it. No hunk overlapped, so git auto-merged the file cleanly. The fix is four lines that delegate to `FakeBroker`, identical to the sibling fake on `Develop` — well inside what the resolution agent does every day, and nothing a human needed to decide.

In `worker/deno/lib/git_pull.ts`, `syncMilestoneBranchWithDefault` runs `resolutionGate` after the commit and, on failure, returns `MilestoneConflictEscalation` with the gate message. There is no path from a failed gate back to the ladder.

## What Needs to Be Done
- `git_pull.ts` / `milestone_conflict_ladder.ts`: when the gate fails after a resolution, offer one bounded **repair** run to the agent rung on the same clone: the prompt carries the gate's failing command and its output tail (the compiler or test failure, not the whole log), the merged-in commits' subjects, and the same never-side-pick contract. The agent edits the files the gate names (which may not be the conflicted files at all), stages, and either commits or leaves the merge for the worker (per the companion issue). Re-run the gate. Escalate only if the repair's gate fails too, with both gate outputs in the escalation.
- The repair counts against the cycle's single agent grant and its timeout (`bindMilestoneConflictAgent`, Issue #1693): if the budget left cannot cover a repair, escalate with the gate output and say the repair was not attempted for want of budget.
- `milestone_sync_conflict.ts`: the merge commit and the sync report name the repair — which files it touched and that the gate passed afterwards — so a reader can tell a textual resolution from a semantic one.
- Fixture and tests: a repository where the default branch adds a trait method and the milestone branch has an implementor the merge does not touch; the gate fails, the injected agent rung adds the method, the gate passes, the push happens; a repair whose gate still fails escalates with both outputs.

## Acceptance Criteria
- [ ] The trait-method fixture syncs without a human, and the merge commit names the repaired file and the rung that repaired it.
- [ ] A repair that fails the gate escalates once with both gate outputs; no second repair is attempted in the same cycle.
- [ ] `./quality.sh` passes.

## Failure Detection
The new fixture test in the worker's Deno suite in CI. In operation, a milestone escalation whose gate output names a compile error in a file git never reported as conflicted is the signature of this gap recurring.

## Context
Reported from the GRQ fleet, alongside #1964, the agent rung's commit being lost. Together they are what "the fleet resolves merge conflicts itself" needs for the two failure shapes seen on `stSoftwareAU/GRQ-AutoTrader#168`: a resolution lost after it was made, and a resolution that was not enough.

**Comment by nleck** [comment]
A second, larger instance from the same fleet, an hour later — stSoftwareAU/GRQ-AutoTrader#304 (`Develop` → `milestone/risk-policy-and-readiness-docs`, which had blocked the milestone PR #281 with the `merge-conflict` label and a "standing down" comment):

- git reported four conflicted files, all resolvable by keeping both sides (a moved loop, a mutable-ledger signature, a doc comment, a README row).
- After that, `cargo check` failed in a file git never touched: the default branch's new IBKR session stores the envelope's capital limits as `Money` and re-checks them at submit; the milestone branch had changed those limits to `CapitalLimit` (absolute **or** a fraction of equity). Neither tree compiled against the other.
- The repair was a real merge of intent, not a side-pick: carry the limit in its authorised form, resolve a fraction against the broker's reported equity at submit, refuse when no equity is observed, add two tests. Then a third semantic conflict surfaced in the milestone's own tests (immutable ledger borrow) and a fourth in an audit-JSON expectation.

So a gate failure can need more than one repair round, and the repair prompt must carry the full compiler output (all errors, not the first) and the diff of both sides for the types involved. The budget clause in the issue should allow up to two repair rounds per cycle before escalating with both gate outputs.

**Comment by VibeCoderST** [comment]
Claimed by `VibeCoderST-1789463242399` on host `vibe-coder-76707`

**Comment by VibeCoderST** [comment]
## Issue run model stats

- **Requested model:** `opus`
- **Served model(s):** `claude-opus-5`
- **Effort:** `high`
- **Issue invocations:** 1
- **Tokens:** input 590 · output 64,486 · cache write 120,558 · cache read 96,468,394
- **Prompt cache:** 99.9% (read 96,468,394 · write 120,558 · uncached 590)
- **Turns:** 295
- **Duration:** 19m 4s
- **Estimated cost (USD, estimate only):** ~$50.60
  - `claude-opus-5`: $50.60 — input $0.0030 · output $1.61 · cache write $0.7535 · cache read $48.23
- **Degraded:** no

_Estimate only — this block covers the run that posted it. The issue total sums the run-stats comments visible on this issue; runs that reported no figures are not included._
